# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fatimg < Formula
  desc "Go utility for creating and managing FAT32 boot (EFI) partition disk images"
  homepage "https://github.com/jsando/fatimg"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsando/fatimg/releases/download/v0.4.1/fatimg_Darwin_x86_64.tar.gz"
      sha256 "e177ba206b0d0eb5994a78d990d2dff81d92a6f8c7464c199883b6e8cbd9970f"

      def install
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsando/fatimg/releases/download/v0.4.1/fatimg_Darwin_arm64.tar.gz"
      sha256 "336a646399ac9af9f73e4ff8f5c0c836c389f0f2c37ac2f66b5fb44e9a2148e3"

      def install
        bin.install "fatimg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.4.1/fatimg_Linux_x86_64.tar.gz"
      sha256 "f879542262f0b9c941bb09d5e4f29e7f035fe9e1d8792280e90e2dd50395bc5d"
      def install
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.4.1/fatimg_Linux_arm64.tar.gz"
      sha256 "04496a6a5f9d0c30d30bca0b819ef169328f7bf6e584b48972873a1f8149fd8f"
      def install
        bin.install "fatimg"
      end
    end
  end

  test do
    system "#{bin}/fatimg", "--version"
  end
end
