# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fatimg < Formula
  desc "Go utility for creating and managing FAT32 boot (EFI) partition disk images"
  homepage "https://github.com/jsando/fatimg"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsando/fatimg/releases/download/v0.4.2/fatimg_Darwin_x86_64.tar.gz"
      sha256 "2b9d5a5ad054aff4ae869c14ea442852fce81d1a8e2da6a7b389913776521e01"

      def install
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsando/fatimg/releases/download/v0.4.2/fatimg_Darwin_arm64.tar.gz"
      sha256 "2bf8be5418733f98a5265c97153d029d24fb8f771af5bdbdf541de2eb9dc8c29"

      def install
        bin.install "fatimg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.4.2/fatimg_Linux_x86_64.tar.gz"
      sha256 "5acc710ea60b66b46f2a72248702ffd83689cd90b7242891871886df248be3b5"
      def install
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.4.2/fatimg_Linux_arm64.tar.gz"
      sha256 "0813f7b00d99991aa117ef0bb16d48c5981b8e15c7723afee47b320e1501cdc7"
      def install
        bin.install "fatimg"
      end
    end
  end

  test do
    system "#{bin}/fatimg", "--version"
  end
end
