# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fatimg < Formula
  desc "Go utility for creating and managing FAT32 boot (EFI) partition disk images"
  homepage "https://github.com/jsando/fatimg"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.0/fatimg_Darwin_x86_64.tar.gz"
      sha256 "60f49895d2364898f0b0c67e88e3e86844fb322eacbdab06476418d3b1acb990"

      def install
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.0/fatimg_Darwin_arm64.tar.gz"
      sha256 "dab699401f318c2f7a324f911c11d5cea98090f8c08a9b0b35797b224d86e7ec"

      def install
        bin.install "fatimg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.0/fatimg_Linux_x86_64.tar.gz"
      sha256 "e28c9105b4879d633fcd396f2477b3052f78a0c3466e52674427d7bc1a8a8177"
      def install
        bin.install "fatimg"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/fatimg/releases/download/v0.5.0/fatimg_Linux_arm64.tar.gz"
      sha256 "08cc50b79c941e1a0be245916c9f3b487851d8c539353d2c74cfb09ef90607b8"
      def install
        bin.install "fatimg"
      end
    end
  end

  test do
    system "#{bin}/fatimg", "--version"
  end
end
