# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jb < Formula
  desc "The Easier Java Build Tool"
  homepage "https://github.com/jsando/jb"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsando/jb/releases/download/v0.1.3/jb-darwin-x86_64.tar.gz"
      sha256 "01bc5bad50f11122b6f1c1a910cd9799e1453bbb502f12a52c12f3bbde7fad5f"

      def install
        bin.install "jb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsando/jb/releases/download/v0.1.3/jb-darwin-arm64.tar.gz"
      sha256 "62ac3558e8d1be09755d2cc421539c83b958cd82ce3d2104c078b488912ddb0b"

      def install
        bin.install "jb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/jb/releases/download/v0.1.3/jb-linux-x86_64.tar.gz"
      sha256 "5096c4bf6a851f9660d7936abc6081509e096aa415f806109470d204b35dd57b"
      def install
        bin.install "jb"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jsando/jb/releases/download/v0.1.3/jb-linux-arm64.tar.gz"
      sha256 "53208dd4987a414552d954cddf68d1730b6a39844f7d86cd8ef296ae92a9d9fb"
      def install
        bin.install "jb"
      end
    end
  end

  test do
    system "#{bin}/jb", "version"
  end
end
